/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gedalias.commandexecution.view;

import com.gedalias.commandexecution.observer.OnUpdateCommandSubject;
import com.gedalias.commandexecution.persist.entity.CommandEntity;
import com.gedalias.commandexecution.persist.repository.CommandRepository;
import com.gedalias.commandexecution.persist.repository.impl.CommandRepositoryImpl;
import com.gedalias.commandexecution.utils.NotificationUtil;
import java.awt.Dimension;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gedalias
 */
public class MainView extends javax.swing.JFrame {
    
    interface CommandValueInputEvent {
        void inputValue(String value);
    }
    
    private JTable table;
    private boolean showComponentOutputCommand = false;
    private Process executedProcess;
    private final String BREAK_LINE = "\n";
    
    private final String[] COLUMNS = new String[]{ "ID","Descrição", "Comando"};
    private final int EXECUTION_PANEL_HEIGHT = 250;
    private final CommandRepository commandRepository = new CommandRepositoryImpl();
    
    private List<CommandEntity> viewDataCommands;
    private CommandEntity selectedCommand;
    
    private CommandValueInputEvent inputValueEvent;

    /**
     * Creates new form MainView
     */
    public MainView() {
        preLoadCommands();
        registerObserver();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        panelCreateCommand = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        descriptionTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        commandTF = new javax.swing.JTextField();
        saveCommandBtn = new javax.swing.JButton();
        deleteCommandBtn = new javax.swing.JButton();
        executeCommandBtn = new javax.swing.JButton();
        resetCommandBtn = new javax.swing.JButton();
        fileChooseBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        scrollCommandShow = new javax.swing.JScrollPane();
        outputCommandTA = new javax.swing.JTextArea();
        stopProcessBtn = new javax.swing.JButton();
        inputParameterCommandTF = new javax.swing.JTextField();
        sendParameterCommandBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buildTable();

        panelCreateCommand.setMaximumSize(new java.awt.Dimension(255, 181));
        panelCreateCommand.setMinimumSize(new java.awt.Dimension(0, 0));
        panelCreateCommand.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Comando");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Descrição:");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Comando:");

        saveCommandBtn.setText("Salvar");
        saveCommandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCommandBtnActionPerformed(evt);
            }
        });

        deleteCommandBtn.setText("Delete");
        deleteCommandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCommandBtnActionPerformed(evt);
            }
        });

        executeCommandBtn.setText("Executar");
        executeCommandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeCommandBtnActionPerformed(evt);
            }
        });

        resetCommandBtn.setText("Reset");
        resetCommandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCommandBtnActionPerformed(evt);
            }
        });

        fileChooseBtn.setText("Buscar Arquivo");
        fileChooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreateCommandLayout = new javax.swing.GroupLayout(panelCreateCommand);
        panelCreateCommand.setLayout(panelCreateCommandLayout);
        panelCreateCommandLayout.setHorizontalGroup(
            panelCreateCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateCommandLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCreateCommandLayout.createSequentialGroup()
                .addGroup(panelCreateCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionTF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(commandTF)
                    .addGroup(panelCreateCommandLayout.createSequentialGroup()
                        .addGroup(panelCreateCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(panelCreateCommandLayout.createSequentialGroup()
                                .addComponent(saveCommandBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteCommandBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(executeCommandBtn))
                            .addGroup(panelCreateCommandLayout.createSequentialGroup()
                                .addComponent(resetCommandBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileChooseBtn)))
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCreateCommandLayout.setVerticalGroup(
            panelCreateCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateCommandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commandTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCreateCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveCommandBtn)
                    .addComponent(deleteCommandBtn)
                    .addComponent(executeCommandBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetCommandBtn)
                    .addComponent(fileChooseBtn))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        outputCommandTA.setColumns(20);
        outputCommandTA.setRows(5);
        scrollCommandShow.setViewportView(outputCommandTA);

        stopProcessBtn.setText("Parar");
        stopProcessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopProcessBtnActionPerformed(evt);
            }
        });

        inputParameterCommandTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputParameterCommandTFActionPerformed(evt);
            }
        });

        sendParameterCommandBtn.setText("Enviar");
        sendParameterCommandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendParameterCommandBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCreateCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sendParameterCommandBtn)
                                    .addComponent(stopProcessBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrollCommandShow)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputParameterCommandTF, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCreateCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stopProcessBtn)
                    .addComponent(scrollCommandShow, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputParameterCommandTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendParameterCommandBtn))
                .addContainerGap())
        );

        showOrHiddenComponentOutputCommand();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeCommandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeCommandBtnActionPerformed
        if(!isSelectedTableRow()) {
            NotificationUtil.showMessage("É necessário selecionar uma linha");
            return;
        }
        
        final int rowPosition = table.getSelectedRow();        
        final String command = viewDataCommands.get(rowPosition).getCommand();
        resetViewCommandExecution();
        executeCommand(command);
        
    }//GEN-LAST:event_executeCommandBtnActionPerformed

    private void saveCommandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCommandBtnActionPerformed
        final String description = descriptionTF.getText();
        final String command = commandTF.getText();
        commandRepository.save(new CommandEntity(null, description, command, 
                LocalDateTime.now(), null));
    }//GEN-LAST:event_saveCommandBtnActionPerformed

    private void stopProcessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopProcessBtnActionPerformed
        executedProcess.destroy();
        outputCommandTA.append("Processo encerrado");
        
    }//GEN-LAST:event_stopProcessBtnActionPerformed

    private void sendParameterCommandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendParameterCommandBtnActionPerformed
        final String parameter = inputParameterCommandTF.getText();
        if(inputValueEvent != null) {
            inputValueEvent.inputValue(parameter);
        }        
    }//GEN-LAST:event_sendParameterCommandBtnActionPerformed

    private void deleteCommandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCommandBtnActionPerformed
        final boolean confirmation = NotificationUtil.confirm("Deseja realmente apagar o registro?");
        if(confirmation) {
            viewDataCommands.remove(selectedCommand);
            refreshDataTable();
            commandRepository.delete(selectedCommand);
        }
    }//GEN-LAST:event_deleteCommandBtnActionPerformed

    private void inputParameterCommandTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputParameterCommandTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputParameterCommandTFActionPerformed

    private void resetCommandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCommandBtnActionPerformed
        selectedCommand = null;
        descriptionTF.setText("");
        commandTF.setText("");
    }//GEN-LAST:event_resetCommandBtnActionPerformed

    private void fileChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseBtnActionPerformed
        JFileChooser fileChoose = new JFileChooser();
        fileChoose.showDialog(this, "Escolher");
        
        final File file = fileChoose.getSelectedFile();
        
        if(file != null) {
            commandTF.setText(file.getAbsolutePath());
        }        
    }//GEN-LAST:event_fileChooseBtnActionPerformed
    
    private void buildTable() {
        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);
        
        Arrays.stream(COLUMNS).forEach(model::addColumn);
        
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table.getColumnModel().getColumn(0).setPreferredWidth(70);
        table.getColumnModel().getColumn(1).setPreferredWidth(250);
        table.getColumnModel().getColumn(2).setPreferredWidth(255);
        
        viewDataCommands.forEach(c -> model.addRow(new String[]{
            String.valueOf(c.getId()), c.getDescription(), c.getCommand()}));
        
        table.getSelectionModel()
            .addListSelectionListener((ListSelectionEvent e) -> {
                final int rowSelectedPosition = table.getSelectedRow();
                if(table.getRowCount() > 0) {
                    selectedCommand = 
                            viewDataCommands.get(rowSelectedPosition);
                    inputSelectedCommand();
                }
            });
        
        scrollPanel.setViewportView(table);
    }
    
    private boolean isSelectedTableRow() {
        return table.getSelectedRow()> -1;
    }
    
    private void preLoadCommands() {
        viewDataCommands = commandRepository.findAll();
    }
    
    private void registerObserver() {
        OnUpdateCommandSubject.getInstance().add((c) -> {
                viewDataCommands.add(c);
                refreshDataTable();
        });
    }
    
    private void executeCommand(String command) {     
        showComponentOutputCommand = true;
        showOrHiddenComponentOutputCommand();
        resizeFrameForCommand();
        new Thread(){
            @Override
            public void run() {
                try {
                    executedProcess = Runtime.getRuntime().exec(command);
                    inputValueEvent = (String value) -> {
                        try {
                            var output = executedProcess.getOutputStream();
                            output.write(value.concat(BREAK_LINE).getBytes());
                            output.flush();
                        } catch (IOException ex) {
                            Logger.getLogger(MainView.class.getName())
                                    .log(Level.SEVERE, null, ex);
                        }
                    };
                    showOutputCommand();
                } catch (IOException ex) {
                    outputCommandTA.setText(ex.getMessage());
                } finally {
                    inputValueEvent = null;
                }
            }
        }.start();
        
    }
    
    private void showOutputCommand() {        
        int line;

        try(BufferedInputStream reader = 
                new BufferedInputStream(executedProcess.getInputStream())) {
            while((line = reader.read()) != -1) {
                outputCommandTA.append(String.valueOf((char)line));
            }
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }
    }
    
    private void resetViewCommandExecution() {
        executedProcess = null;
        outputCommandTA.setText("");
    }
    
    private void showOrHiddenComponentOutputCommand() {
        scrollCommandShow.setVisible(showComponentOutputCommand);
        stopProcessBtn.setVisible(showComponentOutputCommand);
        inputParameterCommandTF.setVisible(showComponentOutputCommand);
        sendParameterCommandBtn.setVisible(showComponentOutputCommand);
    }
    
    private void resizeFrameForCommand() {
        final Dimension actualD = getSize();
        actualD.height = actualD.height+EXECUTION_PANEL_HEIGHT;
        setSize(actualD);
    }
    
    private void inputSelectedCommand() {
        final CommandEntity commandEntity = selectedCommand;
        descriptionTF.setText(commandEntity.getDescription());
        commandTF.setText(commandEntity.getCommand());
    }
    
    private void refreshDataTable() {
        final DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        
        for(CommandEntity c: viewDataCommands) {
            tableModel.addRow(new String[]{String.valueOf(c.getId()), 
                          c.getDescription(), c.getCommand()});
        }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField commandTF;
    private javax.swing.JButton deleteCommandBtn;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JButton executeCommandBtn;
    private javax.swing.JButton fileChooseBtn;
    private javax.swing.JTextField inputParameterCommandTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea outputCommandTA;
    private javax.swing.JPanel panelCreateCommand;
    private javax.swing.JButton resetCommandBtn;
    private javax.swing.JButton saveCommandBtn;
    private javax.swing.JScrollPane scrollCommandShow;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton sendParameterCommandBtn;
    private javax.swing.JButton stopProcessBtn;
    // End of variables declaration//GEN-END:variables
}
